# Generated by Django 5.2.1 on 2025-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('ci', models.CharField(max_length=50)),
                ('nro_tel', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
